using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace His.Entidades.Reportes
{
    public class ReporteInterconsulta
    {
        //public string for_codigo;
        public string for_establecimiento;
        public string for_nombres;
        public string for_apellidos;
        public string for_sexo;
        public string for_edad;
        public string for_historia;
        public string for_est_destino;
        public string for_ser_consulta;
        public string for_ser_solicita;
        public string for_sala;
        public string for_cama;
        public string for_normal;
        public string for_urgente;
        public string for_med_int;
        public string for_desc_motivo;
        public string for_cuadro_clinico;
        public string for_resultado;
        public string for_diag_uno_desc;
        public string for_diag_uno_cie;
        public string for_diag_uno_pre;
        public string for_diag_uno_def;
        public string for_diag_dos_desc;
        public string for_diag_dos_cie;
        public string for_diag_dos_pre;
        public string for_diag_dos_def;
        public string for_diag_tres_desc;
        public string for_diag_tres_cie;
        public string for_diag_tres_pre;
        public string for_diag_tres_def;
        public string for_diag_cuatro_desc;
        public string for_diag_cuatro_cie;
        public string for_diag_cuatro_pre;
        public string for_diag_cuatro_def;
        public string for_diag_cinco_desc;
        public string for_diag_cinco_cie;
        public string for_diag_cinco_pre;
        public string for_diag_cinco_def;
        public string for_diag_seis_desc;
        public string for_diag_seis_cie;
        public string for_diag_seis_pre;
        public string for_diag_seis_def;
        public string for_planes_terap;
        public string for_cuadro_clinico_inter;
        public string for_resumen_criterio;
        public string for_diagnos_uno_desc;
        public string for_diagnos_uno_cie;
        public string for_diagnos_uno_pre;
        public string for_diagnos_uno_def;
        public string for_diagnos_dos_desc;
        public string for_diagnos_dos_cie;
        public string for_diagnos_dos_pre;
        public string for_diagnos_dos_def;
        public string for_diagnos_tres_desc;
        public string for_diagnos_tres_cie;
        public string for_diagnos_tres_pre;
        public string for_diagnos_tres_def;
        public string for_diagnos_cuatro_desc;
        public string for_diagnos_cuatro_cie;
        public string for_diagnos_cuatro_pre;
        public string for_diagnos_cuatro_def;
        public string for_diagnos_cinco_desc;
        public string for_diagnos_cinco_cie;
        public string for_diagnos_cinco_pre;
        public string for_diagnos_cinco_def;
        public string for_diagnos_seis_desc;
        public string for_diagnos_seis_cie;
        public string for_diagnos_seis_pre;
        public string for_diagnos_seis_def;
        public string for_plan_diag;
        public string for_plan_tratamiento;
        public string for_fecha;
        public string for_hora;
        public string for_nom_prof;
        public string for_codigo_prof;
        public string for_num_hoja;
        public string PATH;
        public string interconsu_id;
    }
}
