using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace His.Entidades.Reportes
{
    public class ReporteEpicrisis2
    {

        //public string forCodigo;
        public string forEstablec;
        public string forNombres;
        public string forApellidos;
        public string forSexo;
        public string forHistoria;
        public string forResumenCadro;
        public string forEvolucion;
        public string forHallazgo;
        public string ForResumenTra;
        public string ForDiagIngresoUnoDesc;
        public string ForDiagIngresoUnoCie;
        public string ForDiagIngresoUnoPre;
        public string ForDiagIngresoUnoDef;
        public string ForDiagIngresoDosDesc;
        public string ForDiagIngresoDosCie;
        public string ForDiagIngresoDosPre;
        public string ForDiagIngresoDosDef;
        public string ForDiagIngresoTresDesc;
        public string ForDiagIngresoTresCie;
        public string ForDiagIngresoTresPre;
        public string ForDiagIngresoTresDef;
        public string ForDiagIngresoCuatroDesc;
        public string ForDiagIngresoCuatroCie;
        public string ForDiagIngresoCuatroPre;
        public string ForDiagIngresoCuatroDef;
        public string ForDiagIngresoCincoDesc;
        public string ForDiagIngresoCincoCie;
        public string ForDiagIngresoCincoPre;
        public string ForDiagIngresoCincoDef;
        public string ForDiagIngresoSeisDesc;
        public string ForDiagIngresoSeisCie;
        public string ForDiagIngresoSeisPre;
        public string ForDiagIngresoSeisDef;
        public string ForDiagEgresoUnoDesc;
        public string ForDiagEgresoUnoCie;
        public string ForDiagEgresoUnoPre;
        public string ForDiagEgresoUnoDef;
        public string ForDiagEgresoDosDesc;
        public string ForDiagEgresoDosCie;
        public string ForDiagEgresoDosPre;
        public string ForDiagEgresoDosDef;
        public string ForDiagEgresoTresDesc;
        public string ForDiagEgresoTresCie;
        public string ForDiagEgresoTresPre;
        public string ForDiagEgresoTresDef;
        public string ForDiagEgresoCuatroDesc;
        public string ForDiagEgresoCuatroCie;
        public string ForDiagEgresoCuatroPre;
        public string ForDiagEgresoCuatroDef;
        public string ForDiagEgresoCincoDesc;
        public string ForDiagEgresoCincoCie;
        public string ForDiagEgresoCincoPre;
        public string ForDiagEgresoCincoDef;
        public string ForDiagEgresoSeisDesc;
        public string ForDiagEgresoSeisCie;
        public string ForDiagEgresoSeisPre;
        public string ForDiagEgresoSeisDef;
        public string ForCondEgresoPron;
        public string ForMedicoTratUnoNom;
        public string ForMedicoTratUnoEspec;
        public string ForMedicoTratUnoCodigo;
        public string ForMedicoTratUnoRespo;
        public string ForMedicoTratDosNom;
        public string ForMedicoTratDosEspec;
        public string ForMedicoTratDosCodigo;
        public string ForMedicoTratDosRespo;
        public string ForMedicoTratTresNom;
        public string ForMedicoTratTresEspec;
        public string ForMedicoTratTresCodigo;
        public string ForMedicoTratTresRespo;
        public string ForMedicoTratCuatroNom;
        public string ForMedicoTratCuatroEspec;
        public string ForMedicoTratCuatroCodigo;
        public string ForMedicoTratCuatroRespo;
        public string ForAlataDef;
        public string ForAlataTra;
        public string ForAsintomatico;
        public string ForDiscLeve;
        public string ForDisccModerada;
        public string ForDiscGrave;
        public string ForRetiroAut;
        public string ForRetiroNoAuto;
        public string ForDefuncionMenos;
        public string ForDefucnionMas;
        public int ForDiasEstancia;
        public int ForDiasIncapacidad;
        public DateTime ForFecha;
        public DateTime ForHora;
        public string ForNomProfesional;
        public string ForCodProfesional;
        public int ForNumHoja;
        public string logo;
        public string ForResumenTra1;
    }
}
