USE [His3000]
GO

/****** Object:  Table [dbo].[KARDEX_INSUMOS]    Script Date: 03/03/2021 14:21:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KARDEX_INSUMOS](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[ATE_CODIGO] [bigint] NOT NULL,
	[CUE_CODIGO] [bigint] NOT NULL,
	[PRO_CODIGO] [nvarchar](15) NOT NULL,
	[PRO_DESCRIPCION] [nvarchar](500) NOT NULL,
	[Administrado] [bit] NULL,
	[NoAdministrado] [bit] NULL,
	[fecha] [datetime] NULL,
	[ID_USUARIO] [int] NULL,
	[observacion] [nvarchar](100) NULL,
 CONSTRAINT [PK_KARDEX_INSUMOS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[KARDEX_INSUMOS] ADD  CONSTRAINT [DF_KARDEX_INSUMOS_CUE_CODIGO]  DEFAULT ((0)) FOR [CUE_CODIGO]
GO

ALTER TABLE [dbo].[KARDEX_INSUMOS] ADD  CONSTRAINT [DF_KARDEX_INSUMOS_PRO_CODIGO]  DEFAULT ((0)) FOR [PRO_CODIGO]
GO

ALTER TABLE [dbo].[KARDEX_INSUMOS] ADD  CONSTRAINT [DF_KARDEX_INSUMOS_Administrado]  DEFAULT ((0)) FOR [Administrado]
GO

ALTER TABLE [dbo].[KARDEX_INSUMOS] ADD  CONSTRAINT [DF_KARDEX_INSUMOS_NoAdministrado]  DEFAULT ((0)) FOR [NoAdministrado]
GO

ALTER TABLE [dbo].[KARDEX_INSUMOS] ADD  CONSTRAINT [DF_KARDEX_INSUMOS_fecha]  DEFAULT (((1)-(1))-(1)) FOR [fecha]
GO


