--------------------------------------------------------------09/11/2023---------------------------------------------------------------------
use SERIES3000_AUDITORIA
go
create table PACIENTES_AUD(
ID_PAC_AUD INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
PAC_CODIGO INT NOT NULL,
ID_USUARIO INT NOT NULL,
PAC_FECHA_MODIFICACION DATETIME NOT NULL,
PAC_HISTORIA_CLINICA VARCHAR(50),
DIPO_CODIINEC	VARCHAR(20),
E_CODIGO SMALLINT,
PAC_NOMBRE1	VARCHAR(50),
PAC_NOMBRE2	VARCHAR(50),
PAC_APELLIDO_PATERNO	VARCHAR(50),
PAC_APELLIDO_MATERNO	VARCHAR(50),
PAC_FECHA_NACIMIENTO DATETIME,
PAC_NACIONALIDAD VARCHAR(25),
PAC_TIPO_IDENTIFICACION	VARCHAR(1),
PAC_IDENTIFICACION	VARCHAR(30),
PAC_EMAIL	VARCHAR(50),
PAC_GENERO	CHAR(1),
PAC_IMAGEN	VARCHAR(120),
PAC_ESTADO	BIT,
PAC_DIRECTORIO VARCHAR(250),	
PAC_REFERENTE_NOMBRE	NCHAR(60),
PAC_REFERENTE_PARENTESCO	NCHAR(100),
PAC_REFERENTE_TELEFONO	NCHAR(10),
PAC_ALERGIAS	VARCHAR(250),
PAC_OBSERVACIONES	VARCHAR(500),
GS_CODIGO	SMALLINT,
PAC_REFERENTE_DIRECCION	VARCHAR(250),
PAC_DATOS_INCOMPLETOS BIT
)
GO
--------------------------------------------------------------10/11/2023---------------------------------------------------------------------
use His3000
go 
CREATE TRIGGER TR_PACIENTES_UPDATE
ON dbo.PACIENTES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO SERIES3000_AUDITORIA..PACIENTES_AUD(
        PAC_CODIGO,
		ID_USUARIO,
		PAC_FECHA_MODIFICACION,
        PAC_HISTORIA_CLINICA,        
        DIPO_CODIINEC,
        E_CODIGO,
        PAC_NOMBRE1,
        PAC_NOMBRE2,
        PAC_APELLIDO_PATERNO,
        PAC_APELLIDO_MATERNO,
        PAC_FECHA_NACIMIENTO,
        PAC_NACIONALIDAD,
        PAC_TIPO_IDENTIFICACION,
        PAC_IDENTIFICACION,
        PAC_EMAIL,
        PAC_GENERO,
        PAC_IMAGEN,
        PAC_ESTADO,
        PAC_DIRECTORIO,
        PAC_REFERENTE_NOMBRE,
        PAC_REFERENTE_PARENTESCO,
        PAC_REFERENTE_TELEFONO,
        PAC_ALERGIAS,
        PAC_OBSERVACIONES,
        GS_CODIGO,
        PAC_REFERENTE_DIRECCION,
        PAC_DATOS_INCOMPLETOS
    )
    SELECT
        i.PAC_CODIGO,
		i.ID_USUARIO,
		GETDATE(),
        i.PAC_HISTORIA_CLINICA,        
        i.DIPO_CODIINEC,
        i.E_CODIGO,
        i.PAC_NOMBRE1,
        i.PAC_NOMBRE2,
        i.PAC_APELLIDO_PATERNO,
        i.PAC_APELLIDO_MATERNO,
        i.PAC_FECHA_NACIMIENTO,
        i.PAC_NACIONALIDAD,
        i.PAC_TIPO_IDENTIFICACION,
        i.PAC_IDENTIFICACION,
        i.PAC_EMAIL,
        i.PAC_GENERO,
        i.PAC_IMAGEN,
        i.PAC_ESTADO,
        i.PAC_DIRECTORIO,
        i.PAC_REFERENTE_NOMBRE,
        i.PAC_REFERENTE_PARENTESCO,
        i.PAC_REFERENTE_TELEFONO,
        i.PAC_ALERGIAS,
        i.PAC_OBSERVACIONES,
        i.GS_CODIGO,
        i.PAC_REFERENTE_DIRECCION,
        i.PAC_DATOS_INCOMPLETOS
    FROM
        inserted i
    INNER JOIN
        deleted d ON i.PAC_CODIGO = d.PAC_CODIGO
    WHERE
        i.PAC_ESTADO <> d.PAC_ESTADO
        OR i.PAC_HISTORIA_CLINICA <> d.PAC_HISTORIA_CLINICA
		OR i.DIPO_CODIINEC <> d.DIPO_CODIINEC
        OR i.E_CODIGO <> d.E_CODIGO
        OR i.PAC_NOMBRE1 <> d.PAC_NOMBRE1
        OR i.PAC_NOMBRE2 <> d.PAC_NOMBRE2
        OR i.PAC_APELLIDO_PATERNO <> d.PAC_APELLIDO_PATERNO
        OR i.PAC_APELLIDO_MATERNO <> d.PAC_APELLIDO_MATERNO
        OR i.PAC_FECHA_NACIMIENTO <> d.PAC_FECHA_NACIMIENTO
        OR i.PAC_NACIONALIDAD <> d.PAC_NACIONALIDAD
        OR i.PAC_TIPO_IDENTIFICACION <> d.PAC_TIPO_IDENTIFICACION
        OR i.PAC_IDENTIFICACION <> d.PAC_IDENTIFICACION
        OR i.PAC_EMAIL <> d.PAC_EMAIL
        OR i.PAC_GENERO <> d.PAC_GENERO
        OR i.PAC_IMAGEN <> d.PAC_IMAGEN
        OR i.PAC_ESTADO <> d.PAC_ESTADO
        OR i.PAC_DIRECTORIO <> d.PAC_DIRECTORIO
        OR i.PAC_REFERENTE_NOMBRE <> d.PAC_REFERENTE_NOMBRE
        OR i.PAC_REFERENTE_PARENTESCO <> d.PAC_REFERENTE_PARENTESCO
        OR i.PAC_REFERENTE_TELEFONO <> d.PAC_REFERENTE_TELEFONO
        OR i.PAC_ALERGIAS <> d.PAC_ALERGIAS
        OR i.PAC_OBSERVACIONES <> d.PAC_OBSERVACIONES
        OR i.GS_CODIGO <> d.GS_CODIGO
        OR i.PAC_REFERENTE_DIRECCION <> d.PAC_REFERENTE_DIRECCION
        OR i.PAC_DATOS_INCOMPLETOS <> d.PAC_DATOS_INCOMPLETOS
        -- Aquí debes incluir las demás columnas que quieres monitorear para cambios.

END;

