ALTER PROCEDURE [dbo].[REGISTRO_CAMBIOS] (@codigoPaciente int)  
AS  
SELECT 1 AS N_ORDEN,  
 (SELECT DA.DAP_CODIGO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS DAP_CODIGO,  
 (SELECT DA.DAP_FECHA_INGRESO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS FECHA,  
 (SELECT E.ESC_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ESTADO_CIVIL AS E ON E.ESC_CODIGO = DA.ESC_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS ESTADO_CIVIL,  
 (SELECT DA.DAP_INSTRUCCION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS INSTRUCCION,  
 (SELECT DA.DAP_OCUPACION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS OCUPACION,  
 (SELECT DA.DAP_EMP_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS EMPRESA,  
 (SELECT top 1 TR.TIR_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ATENCIONES AS A ON A.DAP_CODIGO = DA.DAP_CODIGO INNER JOIN TIPO_REFERIDO AS TR ON TR.TIR_CODIGO = A.TIR_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) aS TIPO_SEGURO,  
 (SELECT DA.DAP_DIRECCION_DOMICILIO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS DIRECCION,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS BARRIO,  
 (SELECT TL.TILO_SIMBOLO FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC INNER JOIN TIPO_LOCALIDAD AS TL ON TL.TILO_CODIGO = DP.TILO_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS ZONA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PARROQUIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS PARROQUIA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_CANTON = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS CANTON,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PROVINCIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS PROVINCIA,  
 (SELECT DA.DAP_TELEFONO1 FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 1 AND DA.PAC_CODIGO = @codigoPaciente) AS TELEFONO  
  
 UNION  
SELECT 2 AS N_ORDEN,  
 (SELECT DA.DAP_CODIGO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS DAP_CODIGO,  
 (SELECT DA.DAP_FECHA_INGRESO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS FECHA,  
 (SELECT E.ESC_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ESTADO_CIVIL AS E ON E.ESC_CODIGO = DA.ESC_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS ESTADO_CIVIL,  
 (SELECT DA.DAP_INSTRUCCION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS INSTRUCCION,  
 (SELECT DA.DAP_OCUPACION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS OCUPACION,  
 (SELECT DA.DAP_EMP_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS EMPRESA,  
 (SELECT top 1 TR.TIR_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ATENCIONES AS A ON A.DAP_CODIGO = DA.DAP_CODIGO INNER JOIN TIPO_REFERIDO AS TR ON TR.TIR_CODIGO = A.TIR_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS TIPO_SEGURO,  
 (SELECT DA.DAP_DIRECCION_DOMICILIO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS DIRECCION,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS BARRIO,  
 (SELECT TL.TILO_SIMBOLO FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC INNER JOIN TIPO_LOCALIDAD AS TL ON TL.TILO_CODIGO = DP.TILO_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS ZONA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PARROQUIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS PARROQUIA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_CANTON = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS CANTON,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PROVINCIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS PROVINCIA,  
 (SELECT DA.DAP_TELEFONO1 FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 2 AND DA.PAC_CODIGO = @codigoPaciente) AS TELEFONO  
   
 UNION  
SELECT 3 AS N_ORDEN,  
 (SELECT DA.DAP_CODIGO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS DAP_CODIGO,  
 (SELECT DA.DAP_FECHA_INGRESO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS FECHA,  
 (SELECT E.ESC_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ESTADO_CIVIL AS E ON E.ESC_CODIGO = DA.ESC_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS ESTADO_CIVIL,  
 (SELECT DA.DAP_INSTRUCCION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS INSTRUCCION,  
 (SELECT DA.DAP_OCUPACION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS OCUPACION,  
 (SELECT DA.DAP_EMP_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS EMPRESA,  
 (SELECT top 1 TR.TIR_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ATENCIONES AS A ON A.DAP_CODIGO = DA.DAP_CODIGO INNER JOIN TIPO_REFERIDO AS TR ON TR.TIR_CODIGO = A.TIR_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS TIPO_SEGURO,  
 (SELECT DA.DAP_DIRECCION_DOMICILIO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS DIRECCION,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS BARRIO,  
 (SELECT TL.TILO_SIMBOLO FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC INNER JOIN TIPO_LOCALIDAD AS TL ON TL.TILO_CODIGO = DP.TILO_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS ZONA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PARROQUIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS PARROQUIA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_CANTON = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS CANTON,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PROVINCIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS PROVINCIA,  
 (SELECT DA.DAP_TELEFONO1 FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 3 AND DA.PAC_CODIGO = @codigoPaciente) AS TELEFONO  
   
 UNION  
SELECT 4 AS N_ORDEN,  
 (SELECT DA.DAP_CODIGO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS DAP_CODIGO,  
 (SELECT DA.DAP_FECHA_INGRESO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS FECHA,  
 (SELECT E.ESC_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ESTADO_CIVIL AS E ON E.ESC_CODIGO = DA.ESC_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS ESTADO_CIVIL,  
 (SELECT DA.DAP_INSTRUCCION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS INSTRUCCION,  
 (SELECT DA.DAP_OCUPACION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS OCUPACION,  
 (SELECT DA.DAP_EMP_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS EMPRESA,  
 (SELECT top 1 TR.TIR_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ATENCIONES AS A ON A.DAP_CODIGO = DA.DAP_CODIGO INNER JOIN TIPO_REFERIDO AS TR ON TR.TIR_CODIGO = A.TIR_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) 
AS TIPO_SEGURO,  
 (SELECT DA.DAP_DIRECCION_DOMICILIO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS DIRECCION,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS BARRIO,  
 (SELECT TL.TILO_SIMBOLO FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC INNER JOIN TIPO_LOCALIDAD AS TL ON TL.TILO_CODIGO = DP.TILO_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS ZONA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PARROQUIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS PARROQUIA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_CANTON = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS CANTON,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PROVINCIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS PROVINCIA,  
 (SELECT DA.DAP_TELEFONO1 FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 4 AND DA.PAC_CODIGO = @codigoPaciente) AS TELEFONO

 SELECT 5 AS N_ORDEN,  
 (SELECT DA.DAP_CODIGO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS DAP_CODIGO,  
 (SELECT DA.DAP_FECHA_INGRESO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS FECHA,  
 (SELECT E.ESC_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ESTADO_CIVIL AS E ON E.ESC_CODIGO = DA.ESC_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS ESTADO_CIVIL,  
 (SELECT DA.DAP_INSTRUCCION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS INSTRUCCION,  
 (SELECT DA.DAP_OCUPACION FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS OCUPACION,  
 (SELECT DA.DAP_EMP_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS EMPRESA,  
 (SELECT top 1 TR.TIR_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN ATENCIONES AS A ON A.DAP_CODIGO = DA.DAP_CODIGO INNER JOIN TIPO_REFERIDO AS TR ON TR.TIR_CODIGO = A.TIR_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) 
AS TIPO_SEGURO,  
 (SELECT DA.DAP_DIRECCION_DOMICILIO FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS DIRECCION,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS BARRIO,  
 (SELECT TL.TILO_SIMBOLO FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_SECTOR = DP.DIPO_CODIINEC INNER JOIN TIPO_LOCALIDAD AS TL ON TL.TILO_CODIGO = DP.TILO_CODIGO WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS ZONA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PARROQUIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS PARROQUIA,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_CANTON = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS CANTON,  
 (SELECT DP.DIPO_NOMBRE FROM PACIENTES_DATOS_ADICIONALES AS DA INNER JOIN DIVISION_POLITICA AS DP ON DA.COD_PROVINCIA = DP.DIPO_CODIINEC WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS PROVINCIA,  
 (SELECT DA.DAP_TELEFONO1 FROM PACIENTES_DATOS_ADICIONALES AS DA WHERE DA.DAP_NUMERO_REGISTRO = 5 AND DA.PAC_CODIGO = @codigoPaciente) AS TELEFONO
 
 ---------------------------------------------------------------------------------------------------
 
--VERIFICAR SI 40 ES EL ULTIMO CODIGO DE LA TABLA CUANDO SE VAYA A INSERTAR
select * from PARAMETROS_DETALLE ORDER BY 1 DESC

INSERT INTO PARAMETROS_DETALLE VALUES(40, 8, 'MEDICO CUENTA CONTABLE', NULL, '210101-005', 1)

----------------------------------------------------------------------------------------------------

CREATE PROCEDURE sp_MedicoCuentaContable
AS
SELECT PAD_VALOR FROM PARAMETROS_DETALLE WHERE PAD_CODIGO = 40
GO


----------------------------------------------------------------------------------------------------
---solo alianza a la hora de actualizar
ALTER PROCEDURE [dbo].[sp_RecuperarCuentaPaciente]        
AS        
BEGIN        
select r.RUB_GRUPO, r.RUB_NOMBRE, cp.CUE_FECHA, cp.CUE_DETALLE, cp.PRO_CODIGO_BARRAS, cp.CUE_VALOR_UNITARIO,        
cp.CUE_CANTIDAD, cp.CUE_VALOR, cp.CUE_IVA, cp.DESCUENTO, cp.RUB_CODIGO, cp.RUB_CODIGO, r.RUB_GRUPO, m.MED_CODIGO,        
m.MED_APELLIDO_PATERNO +' '+ m.MED_APELLIDO_MATERNO +' '+ m.MED_NOMBRE1 +' '+ m.MED_APELLIDO_MATERNO,        
cp.CUE_NUM_CONTROL, cp.Id_Tipo_Medico, p.paga_iva  
from ATENCIONES a, CUENTAS_PACIENTES cp, RUBROS r, MEDICOS m, Sic3000..Producto p        
where a.ATE_CODIGO=cp.ATE_CODIGO and cp.RUB_CODIGO=r.RUB_CODIGO and cp.MED_CODIGO=m.MED_CODIGO and    
cp.PRO_CODIGO=p.codpro and   
cp.ATE_CODIGO IN (SELECT ATE_CODIGO FROM AUXAGRUPACION) and cp.CUE_ESTADO=1  order by 1    
end

----------------------------------------------------------------------------------------------------
