select * from Sic3000..SeguridadDepartamento
select * from Sic3000..SeguridadUsuarioOpciones

create table SeguridadesUsuarioGrupo(
codsg bigint identity not null,
codusu bigint not null,
coddep bigint not null,
)
alter table SeguridadesUsuarioGrupo add staopc bit
select * from Cg3000..Cggruopc
select * from Cg3000..Cggrupusu

create table Cgusugrup(
codgu bigint identity not null,
codusu bigint not null,
codgru bigint not null
)
alter table Cgusugrup add staopc bit
---------------------------------------------------------------------------------------------------------------------------------------------------
alter procedure sp_ExploradorProcedimientos      
@desde datetime,            
@hasta datetime, 
@bodega int,
@filtro bit
AS
IF (@filtro = 0)
BEGIN
select (SELECT CASE Q.bodega WHEN 12 THEN 'QUIROFANO' WHEN 19 THEN 'GASTRO' ELSE 'N/A' END) AS 'AREA',Q.fecha_registro AS 'FECHA',P.PAC_HISTORIA_CLINICA AS 'HC',A.ATE_NUMERO_ATENCION AS 'ATENCION',p.PAC_APELLIDO_PATERNO+' '+p.PAC_APELLIDO_MATERNO+' '+p.PAC_NOMBRE1+' '+p.PAC_NOMBRE2 as 'PACIENTE',
(CASE P.PAC_GENERO WHEN 'F' THEN 'FEMENINO' ELSE 'MASCULINO' END) AS 'SEXO',DATEDIFF(YEAR,P.PAC_FECHA_NACIMIENTO,GETDATE()) AS 'EDAD',Q.intervencion AS 'PROCEDIMIENTO',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.cirujano),'N/A') AS 'CIRUJANO',q.hora_inicio as 'HORA INICIO'
,q.hora_fin AS 'HORA FIN',CONCAT(CASE WHEN DATEDIFF(HOUR,hora_inicio,hora_fin)% 24 < 0 THEN DATEDIFF(HOUR,hora_fin,hora_inicio)% 24 ELSE DATEDIFF(HOUR,hora_inicio,hora_fin)% 24  END,':',
CASE WHEN DATEDIFF(MINUTE,hora_inicio,hora_fin)% 60 < 0 THEN DATEDIFF(MINUTE,hora_fin,hora_inicio)% 60 ELSE DATEDIFF(MINUTE,hora_inicio,hora_fin)% 60 END) AS 'TIEMPO CIRUGUA',t.TA_DESCRIPCION
AS 'TIPO ANESTESIA',H.hab_Numero AS 'HABITACION', ISNULL((C.detalle),'N/A') AS 'ESPECIALIDAD CIRUGIA',(SELECT CASE Q.tipo_Atencion WHEN 1 THEN 'PROGRAMADA' ELSE 'EMERGENCIA' END) AS 'TIPO ATENCION',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.instrumentista),'N/A') AS 'INSTRUMENTISTA',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.patologia),'N/A') AS 'PATOLOGO',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.ayudante),'N/A') AS 'AYUDANTE',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.ayudantia),'N/A') AS 'AYUDANTIA',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.anasteciologo),'N/A') AS 'ANESTESIOLOGO',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.anasteciologoAyudante),'N/A') AS 'ANESTESIOLOGO AYUDANTE',
(CASE Q.recuperacion WHEN 1 THEN 'SI' ELSE 'NO' END) AS 'RECUPERACION',(CASE Q.contaminada WHEN 1 THEN 'SI' ELSE 'NO' END) AS 'CONTAMINADA',Q.observaciones AS 'OBSERVACION'
from REGISTRO_QUIROFANO q
inner join ATENCIONES a on q.ate_codigo = a.ate_codigo
inner join PACIENTES p on a.PAC_CODIGO = p.PAC_CODIGO
LEFT join CIRUGIA_ESPECIALIDAD c on q.especialidadCirugia = c.id 
inner join TIPO_ANESTESIA t on q.anestecia = t.TA_CODIGO
INNER JOIN HABITACIONES H ON Q.quirofano = H.hab_Codigo
WHERE q.fecha_registro BETWEEN @desde and @hasta
END
ELSE
BEGIN
select (SELECT CASE Q.bodega WHEN 12 THEN 'QUIROFANO' WHEN 19 THEN 'GASTRO' ELSE 'N/A' END) AS 'AREA',Q.fecha_registro AS 'FECHA',P.PAC_HISTORIA_CLINICA AS 'HC',A.ATE_NUMERO_ATENCION AS 'ATENCION',p.PAC_APELLIDO_PATERNO+' '+p.PAC_APELLIDO_MATERNO+' '+p.PAC_NOMBRE1+' '+p.PAC_NOMBRE2 as 'PACIENTE',
(CASE P.PAC_GENERO WHEN 'F' THEN 'FEMENINO' ELSE 'MASCULINO' END) AS 'SEXO',DATEDIFF(YEAR,P.PAC_FECHA_NACIMIENTO,GETDATE()) AS 'EDAD',Q.intervencion AS 'PROCEDIMIENTO',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.cirujano),'N/A') AS 'CIRUJANO',q.hora_inicio as 'HORA INICIO'
,q.hora_fin AS 'HORA FIN',CONCAT(CASE WHEN DATEDIFF(HOUR,hora_inicio,hora_fin)% 24 < 0 THEN DATEDIFF(HOUR,hora_fin,hora_inicio)% 24 ELSE DATEDIFF(HOUR,hora_inicio,hora_fin)% 24  END,':',
CASE WHEN DATEDIFF(MINUTE,hora_inicio,hora_fin)% 60 < 0 THEN DATEDIFF(MINUTE,hora_fin,hora_inicio)% 60 ELSE DATEDIFF(MINUTE,hora_inicio,hora_fin)% 60 END) AS 'TIEMPO CIRUGUA',t.TA_DESCRIPCION
AS 'TIPO ANESTESIA',H.hab_Numero AS 'HABITACION', ISNULL((C.detalle),'N/A') AS 'ESPECIALIDAD CIRUGIA',(SELECT CASE Q.tipo_Atencion WHEN 1 THEN 'PROGRAMADA' ELSE 'EMERGENCIA' END) AS 'TIPO ATENCION',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.instrumentista),'N/A') AS 'INSTRUMENTISTA',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.patologia),'N/A') AS 'PATOLOGO',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.ayudante),'N/A') AS 'AYUDANTE',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.ayudantia),'N/A') AS 'AYUDANTIA',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.anasteciologo),'N/A') AS 'ANESTESIOLOGO',
ISNULL((SELECT MED_APELLIDO_PATERNO+' '+MED_APELLIDO_MATERNO+' '+MED_NOMBRE1+' '+MED_NOMBRE2 FROM MEDICOS WHERE MED_CODIGO = Q.anasteciologoAyudante),'N/A') AS 'ANESTESIOLOGO AYUDANTE',
(CASE Q.recuperacion WHEN 1 THEN 'SI' ELSE 'NO' END) AS 'RECUPERACION',(CASE Q.contaminada WHEN 1 THEN 'SI' ELSE 'NO' END) AS 'CONTAMINADA',Q.observaciones AS 'OBSERVACION'
from REGISTRO_QUIROFANO q
inner join ATENCIONES a on q.ate_codigo = a.ate_codigo
inner join PACIENTES p on a.PAC_CODIGO = p.PAC_CODIGO
LEFT join CIRUGIA_ESPECIALIDAD c on q.especialidadCirugia = c.id 
inner join TIPO_ANESTESIA t on q.anestecia = t.TA_CODIGO
INNER JOIN HABITACIONES H ON Q.quirofano = H.hab_Codigo
WHERE q.fecha_registro BETWEEN @desde and @hasta and q.bodega = @bodega
END
