-- ALTER PROCEDURE [dbo].[sp_QuirofanoSoloProcedimientos]  
-- AS  
-- SELECT QPP.PCI_CODIGO,  C.PCI_DESCRIPCION AS Procedimiento  
-- FROM QUIROFANO_PROCE_PRODU QPP  
-- INNER JOIN PROCEDIMIENTOS_CIRUGIA C ON QPP.PCI_CODIGO = C.PCI_CODIGO  
-- WHERE QPP.PAC_CODIGO IS NULL  AND C.PCI_ESTADO = 1
-- GROUP BY C.PCI_DESCRIPCION, QPP.PCI_CODIGO ORDER BY 2 ASC  


-- alter PROCEDURE sp_HonorariosAsientoFiltro      
-- @fechaInicio datetime,      
-- @fechaFinal datetime,      
-- @porFuera int,      
-- @porSeguro int, 
-- @id_usuario int,
-- @valor int
-- AS     
-- IF(@valor = 1)
-- BEGIN
	-- SELECT 'false' as Seleccion, dbo.PACIENTES.PAC_HISTORIA_CLINICA as HC, dbo.ATENCIONES.ATE_CODIGO,       
	-- concat(dbo.PACIENTES.PAC_APELLIDO_PATERNO, ' ', dbo.PACIENTES.PAC_APELLIDO_MATERNO, ' ', dbo.PACIENTES.PAC_NOMBRE1, ' ', dbo.PACIENTES.PAC_NOMBRE2) as paciente,  dbo.ATENCIONES.ATE_FACTURA_PACIENTE,     
	-- dbo.MEDICOS.MED_CODIGO,      
	-- CONCAT(dbo.MEDICOS.MED_APELLIDO_PATERNO, ' ', dbo.MEDICOS.MED_APELLIDO_MATERNO, ' ', dbo.MEDICOS.MED_NOMBRE1, ' ',dbo.MEDICOS.MED_NOMBRE2) AS MEDICO,      
	-- dbo.HONORARIOS_MEDICOS.HOM_CODIGO, dbo.HONORARIOS_MEDICOS.HOM_FACTURA_FECHA AS FECHA_FACTURA_MED, 
	-- dbo.HONORARIOS_MEDICOS.HOM_FACTURA_MEDICO as FACTURA,dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.AUTORIZACION_SRI AS AUTORIZACION,
	-- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.FEC_CAD_FACTURA AS CADUCIDAD,       
	-- dbo.HONORARIOS_MEDICOS.HOM_VALOR_NETO as VALOR,      
	-- dbo.HONORARIOS_MEDICOS.HOM_COMISION_CLINICA AS COMISION,      
	-- dbo.HONORARIOS_MEDICOS.HOM_APORTE_LLAMADA AS APORTE,      
	-- dbo.HONORARIOS_MEDICOS.HOM_RETENCION AS RETENCION,       
	-- dbo.RETENCIONES_FUENTE.RET_REFERENCIA as COD_RET,                        
	-- dbo.RETENCIONES_FUENTE.COD_CUE AS CTA_RETENCION ,   
	-- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_CUBIERTO AS VALOR_CUBIERTO,  
	-- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA AS HON_X_FUERA,      
	-- CASE      
	-- WHEN dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = 1 THEN(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR FUERA')      
	-- WHEN dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = 'true' THEN(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR FUERA')      
	-- ELSE(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR DENTRO')      
	-- END AS CTA_HONORARIOS      
	-- , dbo.MEDICOS.MED_CUENTA_CONTABLE AS CTA_MEDICO,      
	-- (select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'APORTE PERSONAL') AS CTA_APORTE      
	-- ,(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'COMISION') AS CTA_COMISION      
	-- ,dbo.HONORARIOS_MEDICOS.HOM_POR_PAGAR AS A_PAGAR,       
	-- ISNULL(dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.GENERADO_ASIENTO, 0) AS GENERADO,      
	-- (select concat(u.NOMBRES,' ',u.APELLIDOS) as USUARIO from USUARIOS u where ID_USUARIO=dbo.HONORARIOS_MEDICOS.ID_USUARIO) AS USUARIO    
	-- , dbo.FORMA_PAGO.forpag,      
	-- 'SEGUROS'= CONVERT(BIT, CASE WHEN (SELECT C.codclas FROM Sic3000..Clasificacion C       
	-- INNER JOIN Sic3000..Forma_Pago FP ON C.codclas = FP.claspag WHERE FORMA_PAGO.forpag = FP.forpag) = 7 THEN 1 else 0 end),    
	-- 'FORMA PAGO' = (SELECT despag FROM Sic3000..Forma_Pago WHERE Sic3000..Forma_Pago.forpag = dbo.FORMA_PAGO.forpag),    
	-- dbo.FORMA_PAGO.FOR_DESCRIPCION  AS 'CORRIENTE / DIFERIDO'    
			   -- FROM dbo.HONORARIOS_MEDICOS_DATOSADICIONALES RIGHT OUTER JOIN      
					   -- dbo.HONORARIOS_MEDICOS INNER JOIN      
						-- dbo.ATENCIONES ON dbo.HONORARIOS_MEDICOS.ATE_CODIGO = dbo.ATENCIONES.ATE_CODIGO INNER JOIN      
						 -- dbo.PACIENTES ON dbo.ATENCIONES.PAC_CODIGO = dbo.PACIENTES.PAC_CODIGO LEFT OUTER JOIN      
						  -- dbo.FORMA_PAGO ON dbo.HONORARIOS_MEDICOS.FOR_CODIGO = dbo.FORMA_PAGO.FOR_CODIGO ON      
						   -- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HOM_CODIGO = dbo.HONORARIOS_MEDICOS.HOM_CODIGO LEFT OUTER JOIN      
							-- dbo.RETENCIONES_FUENTE INNER JOIN      
							 -- dbo.MEDICOS ON dbo.RETENCIONES_FUENTE.RET_CODIGO = dbo.MEDICOS.RET_CODIGO ON dbo.HONORARIOS_MEDICOS.MED_CODIGO = dbo.MEDICOS.MED_CODIGO      
	-- where dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.GENERADO_ASIENTO<>1       
	-- and HONORARIOS_MEDICOS.HOM_FACTURA_FECHA BETWEEN @fechaInicio and @fechaFinal      
	-- AND HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = @porFuera AND 
	-- CONVERT(BIT, CASE WHEN (SELECT C.codclas FROM Sic3000..Clasificacion C 
	-- INNER JOIN Sic3000..Forma_Pago FP ON C.codclas = FP.claspag WHERE FORMA_PAGO.forpag = FP.forpag) = 7 THEN 1 else 0 end) = @porSeguro
	-- AND (SELECT top 1 DEP_CODIGO FROM USUARIOS U 
	-- INNER JOIN HONORARIOS_MEDICOS HM ON U.ID_USUARIO = HM.ID_USUARIO
	-- WHERE HM.ID_USUARIO = @id_usuario) <> 14
-- END
-- ELSE
-- BEGIN
	-- SELECT 'false' as Seleccion, dbo.PACIENTES.PAC_HISTORIA_CLINICA as HC, dbo.ATENCIONES.ATE_CODIGO,       
	-- concat(dbo.PACIENTES.PAC_APELLIDO_PATERNO, ' ', dbo.PACIENTES.PAC_APELLIDO_MATERNO, ' ', dbo.PACIENTES.PAC_NOMBRE1, ' ', dbo.PACIENTES.PAC_NOMBRE2) as paciente,  dbo.ATENCIONES.ATE_FACTURA_PACIENTE,     
	-- dbo.MEDICOS.MED_CODIGO,      
	-- CONCAT(dbo.MEDICOS.MED_APELLIDO_PATERNO, ' ', dbo.MEDICOS.MED_APELLIDO_MATERNO, ' ', dbo.MEDICOS.MED_NOMBRE1, ' ',dbo.MEDICOS.MED_NOMBRE2) AS MEDICO,      
	-- dbo.HONORARIOS_MEDICOS.HOM_CODIGO, dbo.HONORARIOS_MEDICOS.HOM_FACTURA_FECHA AS FECHA_FACTURA_MED, 
	-- dbo.HONORARIOS_MEDICOS.HOM_FACTURA_MEDICO as FACTURA,dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.AUTORIZACION_SRI AS AUTORIZACION,
	-- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.FEC_CAD_FACTURA AS CADUCIDAD,       
	-- dbo.HONORARIOS_MEDICOS.HOM_VALOR_NETO as VALOR,      
	-- dbo.HONORARIOS_MEDICOS.HOM_COMISION_CLINICA AS COMISION,      
	-- dbo.HONORARIOS_MEDICOS.HOM_APORTE_LLAMADA AS APORTE,      
	-- dbo.HONORARIOS_MEDICOS.HOM_RETENCION AS RETENCION,       
	-- dbo.RETENCIONES_FUENTE.RET_REFERENCIA as COD_RET,                        
	-- dbo.RETENCIONES_FUENTE.COD_CUE AS CTA_RETENCION ,   
	-- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_CUBIERTO AS VALOR_CUBIERTO,  
	-- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA AS HON_X_FUERA,      
	-- CASE      
	-- WHEN dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = 1 THEN(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR FUERA')      
	-- WHEN dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = 'true' THEN(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR FUERA')      
	-- ELSE(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR DENTRO')      
	-- END AS CTA_HONORARIOS      
	-- , dbo.MEDICOS.MED_CUENTA_CONTABLE AS CTA_MEDICO,      
	-- (select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'APORTE PERSONAL') AS CTA_APORTE      
	-- ,(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'COMISION') AS CTA_COMISION      
	-- ,dbo.HONORARIOS_MEDICOS.HOM_POR_PAGAR AS A_PAGAR,       
	-- ISNULL(dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.GENERADO_ASIENTO, 0) AS GENERADO,      
	-- (select concat(u.NOMBRES,' ',u.APELLIDOS) as USUARIO from USUARIOS u where ID_USUARIO=dbo.HONORARIOS_MEDICOS.ID_USUARIO) AS USUARIO    
	-- , dbo.FORMA_PAGO.forpag,      
	-- 'SEGUROS'= CONVERT(BIT, CASE WHEN (SELECT C.codclas FROM Sic3000..Clasificacion C       
	-- INNER JOIN Sic3000..Forma_Pago FP ON C.codclas = FP.claspag WHERE FORMA_PAGO.forpag = FP.forpag) = 7 THEN 1 else 0 end),    
	-- 'FORMA PAGO' = (SELECT despag FROM Sic3000..Forma_Pago WHERE Sic3000..Forma_Pago.forpag = dbo.FORMA_PAGO.forpag),    
	-- dbo.FORMA_PAGO.FOR_DESCRIPCION  AS 'CORRIENTE / DIFERIDO'    
			   -- FROM dbo.HONORARIOS_MEDICOS_DATOSADICIONALES RIGHT OUTER JOIN      
					   -- dbo.HONORARIOS_MEDICOS INNER JOIN      
						-- dbo.ATENCIONES ON dbo.HONORARIOS_MEDICOS.ATE_CODIGO = dbo.ATENCIONES.ATE_CODIGO INNER JOIN      
						 -- dbo.PACIENTES ON dbo.ATENCIONES.PAC_CODIGO = dbo.PACIENTES.PAC_CODIGO LEFT OUTER JOIN      
						  -- dbo.FORMA_PAGO ON dbo.HONORARIOS_MEDICOS.FOR_CODIGO = dbo.FORMA_PAGO.FOR_CODIGO ON      
						   -- dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HOM_CODIGO = dbo.HONORARIOS_MEDICOS.HOM_CODIGO LEFT OUTER JOIN      
							-- dbo.RETENCIONES_FUENTE INNER JOIN      
							 -- dbo.MEDICOS ON dbo.RETENCIONES_FUENTE.RET_CODIGO = dbo.MEDICOS.RET_CODIGO ON dbo.HONORARIOS_MEDICOS.MED_CODIGO = dbo.MEDICOS.MED_CODIGO      
	-- where dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.GENERADO_ASIENTO<>1       
	-- and HONORARIOS_MEDICOS.HOM_FACTURA_FECHA BETWEEN @fechaInicio and @fechaFinal      
	-- AND HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = @porFuera AND 
	-- CONVERT(BIT, CASE WHEN (SELECT C.codclas FROM Sic3000..Clasificacion C 
	-- INNER JOIN Sic3000..Forma_Pago FP ON C.codclas = FP.claspag WHERE FORMA_PAGO.forpag = FP.forpag) = 7 THEN 1 else 0 end) = @porSeguro
	-- AND (SELECT top 1 DEP_CODIGO FROM USUARIOS U 
	-- INNER JOIN HONORARIOS_MEDICOS HM ON U.ID_USUARIO = HM.ID_USUARIO
	-- WHERE HM.ID_USUARIO = @id_usuario) = 14
-- END
-- GO


CREATE PROCEDURE sp_AreaYSubArea
@ped_codigo bigint
AS
SELECT RUB_CODIGO, RUB_NOMBRE FROM RUBROS WHERE PED_CODIGO = @ped_codigo
GO


SELECT P.PAC_HISTORIA_CLINICA AS HC, P.PAC_APELLIDO_PATERNO + ' ' + P.PAC_APELLIDO_MATERNO + ' ' + P.PAC_NOMBRE1 + ' ' + P.PAC_NOMBRE2 AS PACIENTE,
A.ATE_NUMERO_ATENCION AS ATENCION, H.hab_Numero AS HAB, A.ATE_FECHA_INGRESO AS 'F. INGRESO', A.ATE_FECHA_ALTA AS 'F. ALTA',
M.MED_APELLIDO_PATERNO + ' ' + M.MED_APELLIDO_MATERNO + ' ' + M.MED_NOMBRE1 + ' ' + M.MED_NOMBRE2 AS MEDICO, 
CP.CUE_FECHA AS 'F. PEDIDO', CP.Codigo_Pedido AS 'N° PEDIDO', U.APELLIDOS + ' ' + U.NOMBRES AS 'SOLICITADO POR', 
PA.PEA_NOMBRE AS AREA, R.RUB_NOMBRE AS SUBAREA, (SELECT TOP 1 SPD.desdep FROM Sic3000..ProductoSubdivision SPS
INNER JOIN Sic3000..ProductoDepartamento SPD ON SPS.codsub = SPD.codSub
WHERE SP.codsub = SPS.codsub)AS DEPARTAMENTO,
SP.despro AS PRODUCTO, SP.codpro AS 'COD. PRODUCTO', A.ATE_FACTURA_PACIENTE AS 'FACTURA',
A.ATE_FACTURA_FECHA AS 'F. FACTURA', CP.CUE_VALOR_UNITARIO AS 'V. UNITARIO', CP.CUE_CANTIDAD AS CANTIDAD, (CP.CUE_CANTIDAD * CUE_VALOR_UNITARIO) AS VALOR,
CP.CUE_IVA AS IVA, ((CP.CUE_CANTIDAD * CUE_VALOR_UNITARIO) + CP.CUE_IVA) AS TOTAL, CC.CAT_NOMBRE AS SEGURO, TR.TIR_NOMBRE AS REFERIDO
FROM Sic3000..Producto SP 
INNER JOIN CUENTAS_PACIENTES CP ON SP.codpro = CP.PRO_CODIGO
INNER JOIN ATENCIONES A ON CP.ATE_CODIGO = A.ATE_CODIGO
INNER JOIN PACIENTES P ON A.PAC_CODIGO = P.PAC_CODIGO
INNER JOIN MEDICOS M ON A.MED_CODIGO = M.MED_CODIGO
INNER JOIN HABITACIONES H ON A.HAB_CODIGO = H.hab_Codigo
INNER JOIN USUARIOS U ON CP.ID_USUARIO = U.ID_USUARIO
INNER JOIN RUBROS R ON CP.RUB_CODIGO = R.RUB_CODIGO
INNER JOIN PEDIDOS_AREAS PA ON R.PED_CODIGO = PA.DIV_CODIGO
INNER JOIN ATENCION_DETALLE_CATEGORIAS ADC ON A.ATE_CODIGO = ADC.ATE_CODIGO
INNER JOIN CATEGORIAS_CONVENIOS CC ON ADC.CAT_CODIGO = CC.CAT_CODIGO
INNER JOIN TIPO_REFERIDO TR ON A.TIR_CODIGO = TR.TIR_CODIGO
