DROP TABLE His3000..HC_HISTOPATOLOGICO
GO
DROP TABLE His3000..HC_HISTOPATOLOGICO_B
GO
DROP TABLE His3000..HC_HISTOPATOLOGIA_B_DETALLE
GO
DROP TABLE His3000..HC_HISTOPATOLOGICO_DIAGNOSTICOS
GO

CREATE TABLE HC_HISTOPATOLOGICO(
HP_CODIGO BIGINT PRIMARY KEY IDENTITY(1,1),
ATE_CODIGO BIGINT,
ESP_CODIGO INT,
HP_PRIORIDAD BIT,
HP_HTOMA TIME,
HP_FTOMA DATE,
HP_HISTOPATOLOGIA VARCHAR(10),
HP_CITOLOGIA VARCHAR(10),
HP_LAMINAS VARCHAR(10),
HP_TRANSOPERATORIO VARCHAR(10),
HP_OTROS VARCHAR(10),
HP_DESCRIPCION VARCHAR(250),
HP_CLINICO VARCHAR(250),
HP_LABORATORIO VARCHAR(250),
HP_IMAGEN VARCHAR(250),
HP_TRATAMIENTO VARCHAR(250),
HP_PROCEDIMIENTO VARCHAR(250),
HP_MUESTRA VARCHAR(250),
HP_ENDOCERVIX VARCHAR(10),
HP_EXOCERVIX VARCHAR(10),
HP_PAREDV VARCHAR(10),
HP_UNION VARCHAR(10),
HP_MUNON VARCHAR(10),
HP_ORAL VARCHAR(10),
HP_DIU VARCHAR(10),
HP_LIGADURA VARCHAR(10),
HP_BARRERA VARCHAR(10),
HP_IMPLANTE VARCHAR(10),
HP_OTRO VARCHAR(10),
HP_TERAPIA VARCHAR(10),
HP_MENARQUIA VARCHAR(10),
HP_MENOPAUSIA VARCHAR(10),
HP_INICIO VARCHAR(10),
HP_GESTA VARCHAR(10),
HP_PARTOS VARCHAR(10),
HP_ABORTOS VARCHAR(10),
HP_CESAREAS VARCHAR(10),
HP_FMENSTRUACION DATETIME,
HP_FPARTO DATETIME,
HP_FCITOLOGIA DATETIME,
HP_DMACROSCOPIA VARCHAR(250),
HP_DCITOLOGIA VARCHAR(250),
HP_BIOLOGIA VARCHAR(250),
HP_HSOLICITUD TIME,
HP_FSOLICITUD DATE,
MED_CODIGO BIGINT,
HP_HRECEPCION TIME,
HP_FRECEPCION DATE,
MED_CODIGO_MUESTRA BIGINT
)
GO

CREATE TABLE  HC_HISTOPATOLOGICO_DIAGNOSTICO(
HPD_CODIGO BIGINT PRIMARY KEY IDENTITY(1,1),
HP_CODIGO BIGINT,
CIE_CODIGO BIGINT,
HPD_TPO NVARCHAR(10),
HDP_DESCRIPCION VARCHAR(250),
HDP_ESTADO BIT,
ID_USUARIO BIGINT
)
GO


alter VIEW [dbo].[HONORARIOS_VISTA] 
as
SELECT     Tm.TMO_NOMBRE, Hm.TMO_CODIGO, Hm.HOM_CODIGO, Hm.ATE_CODIGO, Hm.FOR_CODIGO, Hm.ID_USUARIO, Hm.MED_CODIGO,   
                      Md.MED_APELLIDO_PATERNO + SPACE(1) + Md.MED_NOMBRE1 + SPACE(1) + Md.MED_NOMBRE2 AS MED_NOMBRE_MEDICO, Md.MED_RUC,   
                      Hm.HOM_FACTURA_MEDICO, Hm.HOM_FACTURA_FECHA, Pc.PAC_APELLIDO_PATERNO + SPACE(1) + Pc.PAC_APELLIDO_MATERNO + SPACE(1)   
                      + Pc.PAC_NOMBRE1 + SPACE(1) + Pc.PAC_NOMBRE2 AS PAC_NOMBRE_PACIENTE, Ae.ATE_NUMERO_CONTROL, Ae.ATE_FACTURA_PACIENTE,   
                      Ae.ATE_FACTURA_FECHA, SFP.despag,sfp.forpag,
					  Fp.FOR_DESCRIPCION, Hm.HOM_LOTE, Hm.HOM_FECHA_INGRESO, Hm.HOM_VALOR_NETO, Hm.RET_CODIGO1,   
                      Hm.HOM_RETENCION, Hm.HOM_COMISION_CLINICA, Hm.HOM_APORTE_LLAMADA, Hm.HOM_VALOR_TOTAL,   
                      Hm.HOM_VALOR_NETO - Hm.HOM_COMISION_CLINICA AS VALOR_POR_RECUPERAR, Hm.HOM_RECORTE, Hm.HOM_OBSERVACION,   
                      Hm.HOM_VALOR_PAGADO, Hm.HOM_VALOR_CANCELADO, Hm.HOM_VALOR_TOTAL AS VALOR_RECUPERADO,   
                      Hm.HOM_VALOR_TOTAL - Hm.HOM_VALOR_CANCELADO AS DIFERENCIA,   
       HMD.HON_FUERA, U.APELLIDOS + ' ' + U.NOMBRES AS RESPONSABLE,  
       TR.TIR_NOMBRE AS REFERIDO
FROM dbo.HONORARIOS_MEDICOS AS Hm   
INNER JOIN dbo.MEDICOS AS Md ON Hm.MED_CODIGO = Md.MED_CODIGO   
INNER JOIN HONORARIOS_MEDICOS_DATOSADICIONALES HMD ON Hm.HOM_CODIGO = HMD.HOM_CODIGO  
INNER JOIN USUARIOS U ON HM.ID_USUARIO = U.ID_USUARIO  
INNER JOIN dbo.TIPO_MOVIMIENTO AS Tm ON Hm.TMO_CODIGO = Tm.TMO_CODIGO 
LEFT OUTER JOIN dbo.FORMA_PAGO AS Fp ON Hm.FOR_CODIGO = Fp.FOR_CODIGO   
INNER JOIN Sic3000..Forma_Pago SFP ON Fp.forpag = SFP.forpag  
LEFT OUTER JOIN dbo.ATENCIONES AS Ae ON Hm.ATE_CODIGO = Ae.ATE_CODIGO 
LEFT OUTER JOIN dbo.PACIENTES AS Pc ON Ae.PAC_CODIGO = Pc.PAC_CODIGO  
INNER JOIN TIPO_REFERIDO TR ON Ae.TIR_CODIGO = TR.TIR_CODIGO  