CREATE TABLE PREADMISION(
PRE_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
PRE_IDENTIFICACION NVARCHAR(25),
PRE_NOMBRE1 NVARCHAR(255),
PRE_NOMBRE2 NVARCHAR(255),
PRE_APELLIDO1 NVARCHAR(255),
PRE_APELLIDO2 NVARCHAR(255),
PRE_DIRECCION NVARCHAR(500),
PRE_TELEFONO NVARCHAR(15),
PRE_CELULAR NVARCHAR(15),
PRE_EMAIL NVARCHAR(50),
MED_CODIGO BIGINT,
TIA_CODIGO INT,
TIR_CODIGO INT,
PRE_ESTADO BIT,
PRE_FECHA DATETIME,
ID_USUARIO INT)

CREATE TABLE PREADMISION_DETALLE
(PRD_CODIGO BIGINT IDENTITY(1,1) PRIMARY KEY,
PRE_CODIGO BIGINT,
CIE_CODIGO NVARCHAR(10))