alter procedure [dbo].[sp_ImpresionPedidoMushuñan]( @Pedido as int)        
as        
begin        
 select         
 PACIENTES.PAC_APELLIDO_PATERNO + ' ' + PACIENTES.PAC_APELLIDO_MATERNO + ' ' +PACIENTES.PAC_NOMBRE1 + ' ' +PACIENTES.PAC_NOMBRE2 AS PACIENTE,         
 PACIENTES.PAC_IDENTIFICACION AS IDENTIFICACION,        
 PEDIDOS.PED_FECHA,        
 PEDIDOS.PED_CODIGO AS [NUMERO PEDIDO],        
 pedidos.ID_USUARIO AS [CODIGO USUARIO],         
 USUARIOS.USR AS USUARIO ,        
 MEDICOS.MED_APELLIDO_PATERNO + ' ' + MEDICOS.MED_APELLIDO_MATERNO + ' ' + MEDICOS.MED_NOMBRE1 + ' ' + MEDICOS.MED_NOMBRE2 as MEDICOS,        
 PRO_CODIGO,        
 dbo.datosproducto(PRO_CODIGO) as Producto,        
 PDD_CANTIDAD,        
 PDD_VALOR,        
 PDD_IVA,        
 PDD_TOTAL,    
 PAC_HISTORIA_CLINICA as HISTORIA,    
 ATENCIONES.ATE_NUMERO_ATENCION AS ATENCION,    
 (SELECT HABITACIONES.hab_Numero FROM HABITACIONES WHERE HABITACIONES.hab_Codigo=ATENCIONES.HAB_CODIGO)  AS HABITACION,    
 'DISPENSARIO SANTA CATALINA DE SENA' AS ESTACION  ,  
 (SELECT TOP (1) dbo.CATEGORIAS_CONVENIOS.CAT_NOMBRE  
   FROM  dbo.ATENCIONES aa INNER JOIN dbo.ATENCION_DETALLE_CATEGORIAS ON aa.ATE_CODIGO = dbo.ATENCION_DETALLE_CATEGORIAS.ATE_CODIGO INNER JOIN dbo.CATEGORIAS_CONVENIOS ON dbo.ATENCION_DETALLE_CATEGORIAS.CAT_CODIGO = dbo.CATEGORIAS_CONVENIOS.CAT_CODIGO  
   WHERE aa.ATE_CODIGO = ATENCIONES.ATE_CODIGO) as ASEGURADORA, PEDIDOS.PED_DESCRIPCION AS OBSERVACION  
 from pedidos,PEDIDOS_DETALLE,USUARIOS,MEDICOS,ATENCIONES,PACIENTES        
 where pedidos.ID_USUARIO=USUARIOS.ID_USUARIO        
 and MEDICOS.MED_CODIGO= ATENCIONES.MED_CODIGO      
 AND PEDIDOS.PED_CODIGO=PEDIDOS_DETALLE.PED_CODIGO        
 and PEDIDOS.PED_CODIGO=@Pedido        
 and pacientes.PAC_CODIGO=ATENCIONES.PAC_CODIGO        
 and ATENCIONES.ATE_CODIGO=pedidos.ATE_CODIGO  
 AND PEDIDOS_DETALLE.PDD_CANTIDAD > 0  
 order by PRO_CODIGO        
end  


------------------------------------------------------------------------
alter PROCEDURE [dbo].[sp_CertificadoPaciente]    
@ate_codigo bigint    
AS    
SELECT p.PAC_APELLIDO_PATERNO, p.PAC_APELLIDO_MATERNO, p.PAC_NOMBRE1, p.PAC_NOMBRE2, A.ATE_CODIGO    
, TI.TIP_DESCRIPCION, PAC_IDENTIFICACION, p.PAC_FECHA_NACIMIENTO, p.PAC_NACIONALIDAD, p.PAC_GENERO,    
(select top 1 EMP_NOMBRE from EMPRESA), a.ATE_NUMERO_ATENCION, TI.TIP_CODIGO  
from PACIENTES p     
inner join ATENCIONES a on p.PAC_CODIGO = a.PAC_CODIGO    
inner join TIPO_INGRESO TI on a.TIP_CODIGO = ti.TIP_CODIGO    
where a.ATE_CODIGO = @ate_codigo 

---------------------------------------------------


alter PROCEDURE sp_Certificado_Mostrar  
@ate_codigo int  
AS  
SELECT TOP 1 P.PAC_APELLIDO_PATERNO + ' ' + P.PAC_APELLIDO_MATERNO + ' ' + P.PAC_NOMBRE1 + ' ' +P.PAC_NOMBRE2 AS PACIENTE,  
P.PAC_IDENTIFICACION, P.PAC_HISTORIA_CLINICA, A.ATE_FECHA_INGRESO, A.ATE_FECHA_ALTA,   
CM.CER_DIAS_REPOSO, M.MED_APELLIDO_PATERNO + ' ' + M.MED_APELLIDO_MATERNO + ' ' + M.MED_NOMBRE1 + ' ' + M.MED_NOMBRE2 AS MEDICO,  
M.MED_RUC, M.MED_EMAIL, CM.CER_CODIGO, CM.CER_OBSERVACION, (SELECT top 1 EMP_NOMBRE FROM EMPRESA), (SELECT top 1 EMP_DIRECCION FROM EMPRESA),  
(SELECT top 1 EMP_TELEFONO FROM EMPRESA)  
FROM CERTIFICADO_MEDICO CM  
INNER JOIN ATENCIONES A ON CM.ATE_CODIGO = A.ATE_CODIGO  
INNER JOIN PACIENTES P ON A.PAC_CODIGO = P.PAC_CODIGO  
INNER JOIN MEDICOS M ON A.MED_CODIGO = M.MED_CODIGO  
WHERE CM.ATE_CODIGO = @ate_codigo  
ORDER BY CM.CER_FECHA DESC  

-----------------------------------------------------------
ALTER TABLE autorizacion
--ADD nestablecimiento NVARCHAR(3)
ADD codlocal FLOAT DEFAULT 10

-----------------------------------------------------
CREATE PROCEDURE sp_ValidarPEmision
@caja nvarchar(4)
AS
SELECT nestablecimiento FROM Sic3000..autorizacion WHERE caja = @caja