
alter table HC_INGESTA_ELIMINACION_DETALLE add IED_DETALLE NVARCHAR (150)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(64,1,'TIEMPO HORAS TRANSCURRIDO PARA GENERAR EPICRISIS',NULL,'2',1)
GO
alter procedure sp_grabarDetalleEliminacion            
@IED_CODIGO INT,            
@IED_TIPO VARCHAR (10),            
@IED_HORA TIME(7),            
@IED_CLASE VARCHAR (150),            
@IED_CANTIDAD VARCHAR (10),            
@IE_CODIGO INT,    
@ID_USUARIO int,    
@MODO VARCHAR(10),
@IED_DETALLE varchar(MAX)
as             
IF exists(select * from HC_INGESTA_ELIMINACION_DETALLE where IED_CODIGO = @IED_CODIGO)            
BEGIN            
UPDATE HC_INGESTA_ELIMINACION_DETALLE SET IED_HORA = @IED_HORA,IED_CLASE=@IED_CLASE,IED_CANTIDAD=@IED_CANTIDAD            
WHERE IED_CODIGO = @IED_CODIGO            
END            
else            
BEGIN            
insert into HC_INGESTA_ELIMINACION_DETALLE (IED_TIPO,IED_HORA,IED_CLASE,IED_CANTIDAD,IE_CODIGO,ID_USUARIO,IED_DETALLE)            
values (@IED_TIPO,@IED_HORA,@IED_CLASE,@IED_CANTIDAD,@IE_CODIGO,@ID_USUARIO,@IED_DETALLE)            
END
GO
ALTER TABLE MEDICAMENTO_COMPUESTO_ENCABEZADO ADD v_infucion NVARCHAR(150)
GO
ALTER TABLE MEDICAMENTO_COMPUESTO_ENCABEZADO ADD n_aplicacion NVARCHAR(150)
GO

drop table [HC_CONSENTIMIENTO_INFORMADO]
GO
CREATE TABLE [dbo].[HC_CONSENTIMIENTO_INFORMADO](
	[CON_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATE_CODIGO] [bigint] NULL,
	[CON_SERVICIO] [varchar](100) NULL,
	[CON_SALA] [varchar](10) NULL,
	[CON_PROPOSITO1] [varchar](500) NULL,
	[CON_RESULTADO1] [varchar](500) NULL,
	[CON_PROCEDIMIENTO] [varchar](500) NULL,
	[CON_RIESGO1] [varchar](500) NULL,
	[CON_PROPOSITO2] [varchar](500) NULL,
	[CON_RESULTADO2] [varchar](500) NULL,
	[CON_QUIRURGICO] [varchar](500) NULL,
	[CON_RIESGO2] [varchar](500) NULL,
	[CON_PROPOSITO3] [varchar](500) NULL,
	[CON_RESULTADO3] [varchar](500) NULL,
	[CON_ANESTESIA] [varchar](500) NULL,
	[CON_RIESGO3] [varchar](500) NULL,
	[CON_FECHA] [date] NULL,
	[CON_HORA] [time](7) NULL,
	[CON_TRATANTE] [varchar](100) NULL,
	[CON_TESPECIALIDAD] [varchar](100) NULL,
	[CON_TTELEFONO] [varchar](10) NULL,
	[CON_TCODIGO] [varchar](10) NULL,
	[CON_CIRUJANO] [varchar](100) NULL,
	[CON_CESPECIALIDAD] [varchar](100) NULL,
	[CON_CTELEFONO] [varchar](10) NULL,
	[CON_CCODIGO] [varchar](10) NULL,
	[CON_ANESTESISTA] [varchar](100) NULL,
	[CON_AESPECIALIDAD] [varchar](100) NULL,
	[CON_ATELEFONO] [varchar](10) NULL,
	[CON_ACODIGO] [varchar](10) NULL,
	[CON_REPRESENTANTE] [varchar](100) NULL,
	[CON_PARENTESCO] [varchar](100) NULL,
	[CON_IDENTIFICACION] [varchar](15) NULL,
	[CON_TELEFONO] [varchar](10) NULL
 CONSTRAINT [PK_HC_CONSENTIMIENTO_INFORMADO] PRIMARY KEY CLUSTERED 
(
	[CON_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
drop table HC_EXONERACION_RETIRO
GO
CREATE TABLE [dbo].[HC_EXONERACION_RETIRO](
	[ER_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ATE_CODIGO] [bigint] NULL,
	[ER_PDTESTIGO] [varchar](100) NULL,
	[ER_PDPARENTESCO] [varchar](100) NULL,
	[ER_PDTELEFONO] [varchar](10) NULL,
	[ER_PDCEDULA] [varchar](15) NULL,
	[ER_ABTESTIGO] [varchar](100) NULL,
	[ER_ABPARENTESCO] [varchar](100) NULL,
	[ER_ABTELEFONO] [varchar](10) NULL,
	[ER_ABCEDULA] [varchar](15) NULL,
	[ER_AHMEDICO] [varchar](100) NULL,
	[ER_AHTELEFONO] [varchar](10) NULL,
	[ER_AHCEDULA] [varchar](15) NULL,
	[ER_AHTTESTIGO] [varchar](100) NULL,
	[ER_AHTPARENTESCO] [varchar](100) NULL,
	[ER_AHTTELEFONO] [varchar](10) NULL,
	[ER_AHTCEDULA] [varchar](15) NULL,
	[ER_MEMEDICO] [varchar](100) NULL,
	[ER_METELEFONO] [varchar](10) NULL,
	[ER_MECEDULA] [varchar](15) NULL,
	[ER_METTESTIGO] [varchar](100) NULL,
	[ER_METPARENTESCO] [varchar](100) NULL,
	[ER_METTELEFONO] [varchar](10) NULL,
	[ER_METCEDULA] [varchar](15) NULL,
	[ER_ODMEDICO] [varchar](100) NULL,
	[ER_ODTELEFONO] [varchar](10) NULL,
	[ER_ODCEDULA] [varchar](15) NULL,
	[ER_ODTTESTIGO] [varchar](100) NULL,
	[ER_ODTPARENTESCO] [varchar](100) NULL,
	[ER_ODTTELEFONO] [varchar](10) NULL,
	[ER_ODTCEDULA] [varchar](15) NULL,
	[ER_ANMEDICO] [varchar](100) NULL,
	[ER_ANTELEFONO] [varchar](10) NULL,
	[ER_ANCEDULA] [varchar](15) NULL,
	[ER_ANTTESTIGO] [varchar](100) NULL,
	[ER_ANTPARENTESCO] [varchar](100) NULL,
	[ER_ANTTELEFONO] [varchar](10) NULL,
	[ER_ANTCEDULA] [varchar](15) NULL,
	[ER_REPRESENTANTE] [varchar](100) NULL,
	[ER_PARENTESCO] [varchar](100) NULL,
	[ER_IDENTIFICACION] [varchar](15) NULL,
	[ER_TELEFONO] [varchar](10) NULL,
	[ER_ORGANOS_DONADOS] [varchar](200) NULL,
	[ER_NOMBRE_RECEPTOR] [varchar](300) NULL,
	[ER_ESTA1] [bit] NULL,
	[ER_ESTA2] [bit] NULL,
	[ER_ESTA3] [bit] NULL,
	[ER_ESTA4] [bit] NULL,
	[ER_ESTA5] [bit] NULL,
	[ER_ESTA6] [bit] NULL,
 CONSTRAINT [PK_HC_EXONERACION_RETIRO] PRIMARY KEY CLUSTERED 
(
	[ER_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
