USE [His3000]
GO

/****** Object:  Table [dbo].[HONORARIOS_CONSULTA_EXTERNA]    Script Date: 26/12/2023 09:24:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HONORARIOS_CONSULTA_EXTERNA](
	[HCE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRO_CODIGO] [varchar](10) NULL,
	[PRO_DESCRIPCION] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[HCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


