INSERT INTO PARAMETROS VALUES(29,4,'SIGNOS VITALES','SE VARAMETRIZAN TODOS LOS DATOS PARA LA TOMA DE SIGNOS VITALES',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(54,29,'PRESION ARTERIAL MINIMA',NULL,'200',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(55,29,'PRESION ARTERIAL MAXIMA',NULL,'300',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(56,29,'FRECUENCIA CARDIACA MINIMA',NULL,'20',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(57,29,'FRECUENCIA CARDIACA MAXIMA',NULL,'200',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(58,29,'FRECUENCIA RESPIRATORIA MINIMA',NULL,'14',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(59,29,'FRECUENCIA RESPIRATORIA MAXIMA',NULL,'60',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(60,29,'TEMPERATURA MINIMA',NULL,'34',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(61,29,'TEMPERATURA MAXIMA',NULL,'40',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(62,29,'SATURACION OXIGENO MINIMA',NULL,'30',1)
GO
INSERT INTO PARAMETROS_DETALLE VALUES(63,29,'SATURACION OXIGENO MAXIMA',NULL,'100',1)
GO
INSERT INTO VIA_ADMINISTRACION_MEDICAMENTO VALUES ('ENTERAL')
GO
INSERT INTO FRECUENCIA VALUES ('CADA HORA')
GO
CREATE TABLE TIPO_DIETA(
TDI_CODIGO INT IDENTITY(1,1),
TDI_DESCRIPCION VARCHAR (50)
)
GO

CREATE TABLE TIPO_DRENAJE(
TDR_CODIGO INT IDENTITY(1,1),
TDR_DESCRIPCION VARCHAR(50)
)
GO

INSERT INTO TIPO_DIETA VALUES ('Dieta general') 
INSERT INTO TIPO_DIETA VALUES ('Dieta Blanda intestinal') 
INSERT INTO TIPO_DIETA VALUES ('Dieta gástrica') 
INSERT INTO TIPO_DIETA VALUES ('Dieta hiposódica') 
INSERT INTO TIPO_DIETA VALUES ('Dieta para diabético') 
INSERT INTO TIPO_DIETA VALUES ('Dieta hiperproteica') 
INSERT INTO TIPO_DIETA VALUES ('Dieta blanda astringente') 
INSERT INTO TIPO_DIETA VALUES ('Dieta hipocalórica') 
INSERT INTO TIPO_DIETA VALUES ('Dieta vegetariana o vegana') 
INSERT INTO TIPO_DIETA VALUES ('Dieta líquida estricta') 
INSERT INTO TIPO_DIETA VALUES ('Dieta líquida amplia') 
INSERT INTO TIPO_DIETA VALUES ('Nada por vía oral') 

INSERT INTO TIPO_DRENAJE VALUES ('Jackson') 
INSERT INTO TIPO_DRENAJE VALUES ('Hemovac') 
INSERT INTO TIPO_DRENAJE VALUES ('Penrrose') 
INSERT INTO TIPO_DRENAJE VALUES ('kehr o tubo en T') 
INSERT INTO TIPO_DRENAJE VALUES ('Sonda nasogástrica') 
INSERT INTO TIPO_DRENAJE VALUES ('Tubo torácico') 
INSERT INTO TIPO_DRENAJE VALUES ('OTROS') 
