-- SELECT * FROM PARAMETROS ORDER BY 1 DESC

-- INSERT INTO PARAMETROS VALUES(19, 1, 'NUMERO DE VALE', 'AUTOINCREMENTABLE', 1)

-- SELECT * FROM PARAMETROS_DETALLE ORDER BY 1 DESC

-- INSERT INTO PARAMETROS_DETALLE VALUES(30, 19, 'NUMERO DE VALE', NULL, '1000', 1)

-- CREATE PROCEDURE sp_HFomasPago
-- @forcodigo INT
-- AS
-- SELECT SFP.despag FROM FORMA_PAGO FP 
-- INNER JOIN Sic3000..Forma_Pago SFP ON FP.forpag = SFP.forpag
-- WHERE FP.FOR_CODIGO = @forcodigo
-- GO

alter PROCEDURE sp_HonorariosDetalleReporte
@ate_codigo bigint
AS
SELECT P.PAC_APELLIDO_PATERNO + ' ' + P.PAC_APELLIDO_MATERNO + ' ' + P.PAC_NOMBRE1 + ' ' + P.PAC_NOMBRE2 AS PACIENTE,
'DIRECCION' = (SELECT TOP 1 PDA.DAP_DIRECCION_DOMICILIO FROM PACIENTES_DATOS_ADICIONALES PDA WHERE PDA.PAC_CODIGO = P.PAC_CODIGO), 
A.ATE_FECHA_INGRESO, A.ATE_FECHA_ALTA, P.PAC_IDENTIFICACION AS CEDULA, A.ATE_FACTURA_PACIENTE,
P.PAC_HISTORIA_CLINICA AS HC, A.ATE_NUMERO_ATENCION AS NUMATENCION, H.hab_Numero AS HAB,
M.MED_APELLIDO_PATERNO + ' ' + M.MED_APELLIDO_MATERNO + ' ' + M.MED_NOMBRE1 + ' ' + M.MED_NOMBRE2 AS MEDICO,
HM.HOM_FACTURA_MEDICO AS FACTURAMEDICO, HM.HOM_FECHA_INGRESO AS FECHAH, HM.HOM_VALOR_NETO AS NETO, HM.HOM_COMISION_CLINICA AS COMISION,
HM.HOM_APORTE_LLAMADA AS APORTE, HM.HOM_RETENCION AS RETENCION, HM.VALOR AS CUBIERTO, HM.HOM_VALOR_TOTAL AS TOTAL, 
SFP.despag AS 'FORMA_PAGO', FP.FOR_DESCRIPCION AS 'DIFIERE DE', TI.TIR_NOMBRE AS REFERIDO, U.APELLIDOS + ' ' + U.NOMBRES AS USUARIO,
HM.HOM_VALE
FROM HONORARIOS_MEDICOS HM
INNER JOIN ATENCIONES A ON HM.ATE_CODIGO = A.ATE_CODIGO
INNER JOIN PACIENTES P ON A.PAC_CODIGO = P.PAC_CODIGO
INNER JOIN FORMA_PAGO FP ON HM.FOR_CODIGO = FP.FOR_CODIGO
INNER JOIN Sic3000..Forma_Pago SFP ON FP.forpag = SFP.forpag
INNER JOIN HABITACIONES H ON A.HAB_CODIGO = H.hab_Codigo
INNER JOIN MEDICOS M ON HM.MED_CODIGO = M.MED_CODIGO
INNER JOIN TIPO_REFERIDO TI ON A.TIR_CODIGO = TI.TIR_CODIGO
INNER JOIN USUARIOS U ON HM.ID_USUARIO = U.ID_USUARIO
WHERE HM.ATE_CODIGO = @ate_codigo
GO




alter PROCEDURE sp_HonorariosAsientoFiltro      
@fechaInicio datetime,      
@fechaFinal datetime,      
@porFuera int,      
@porSeguro int, 
@id_usuario int
AS       
SELECT 'false' as Seleccion, dbo.PACIENTES.PAC_HISTORIA_CLINICA as HC, dbo.ATENCIONES.ATE_CODIGO,       
concat(dbo.PACIENTES.PAC_APELLIDO_PATERNO, ' ', dbo.PACIENTES.PAC_APELLIDO_MATERNO, ' ', dbo.PACIENTES.PAC_NOMBRE1, ' ', dbo.PACIENTES.PAC_NOMBRE2) as paciente,  dbo.ATENCIONES.ATE_FACTURA_PACIENTE,     
dbo.MEDICOS.MED_CODIGO,      
CONCAT(dbo.MEDICOS.MED_APELLIDO_PATERNO, ' ', dbo.MEDICOS.MED_APELLIDO_MATERNO, ' ', dbo.MEDICOS.MED_NOMBRE1, ' ',dbo.MEDICOS.MED_NOMBRE2) AS MEDICO,      
dbo.HONORARIOS_MEDICOS.HOM_CODIGO, dbo.HONORARIOS_MEDICOS.HOM_FACTURA_FECHA AS FECHA_FACTURA_MED, 
dbo.HONORARIOS_MEDICOS.HOM_FACTURA_MEDICO as FACTURA,dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.AUTORIZACION_SRI AS AUTORIZACION,
dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.FEC_CAD_FACTURA AS CADUCIDAD,       
dbo.HONORARIOS_MEDICOS.HOM_VALOR_NETO as VALOR,      
dbo.HONORARIOS_MEDICOS.HOM_COMISION_CLINICA AS COMISION,      
dbo.HONORARIOS_MEDICOS.HOM_APORTE_LLAMADA AS APORTE,      
dbo.HONORARIOS_MEDICOS.HOM_RETENCION AS RETENCION,       
dbo.RETENCIONES_FUENTE.RET_REFERENCIA as COD_RET,                        
dbo.RETENCIONES_FUENTE.COD_CUE AS CTA_RETENCION ,   
dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_CUBIERTO AS VALOR_CUBIERTO,  
dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA AS HON_X_FUERA,      
CASE      
WHEN dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = 1 THEN(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR FUERA')      
WHEN dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = 'true' THEN(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR FUERA')      
ELSE(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'HONORARIOS POR DENTRO')      
END AS CTA_HONORARIOS      
, dbo.MEDICOS.MED_CUENTA_CONTABLE AS CTA_MEDICO,      
(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'APORTE PERSONAL') AS CTA_APORTE      
,(select PAD_VALOR from PARAMETROS_DETALLE where PAD_NOMBRE like 'COMISION') AS CTA_COMISION      
,dbo.HONORARIOS_MEDICOS.HOM_POR_PAGAR AS A_PAGAR,       
ISNULL(dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.GENERADO_ASIENTO, 0) AS GENERADO,      
(select concat(u.NOMBRES,' ',u.APELLIDOS) as USUARIO from USUARIOS u where ID_USUARIO=dbo.HONORARIOS_MEDICOS.ID_USUARIO) AS USUARIO    
, dbo.FORMA_PAGO.forpag,      
'SEGUROS'= CONVERT(BIT, CASE WHEN (SELECT C.codclas FROM Sic3000..Clasificacion C       
INNER JOIN Sic3000..Forma_Pago FP ON C.codclas = FP.claspag WHERE FORMA_PAGO.forpag = FP.forpag) = 7 THEN 1 else 0 end),    
'FORMA PAGO' = (SELECT despag FROM Sic3000..Forma_Pago WHERE Sic3000..Forma_Pago.forpag = dbo.FORMA_PAGO.forpag),    
dbo.FORMA_PAGO.FOR_DESCRIPCION  AS 'CORRIENTE / DIFERIDO'    
           FROM dbo.HONORARIOS_MEDICOS_DATOSADICIONALES RIGHT OUTER JOIN      
                   dbo.HONORARIOS_MEDICOS INNER JOIN      
                    dbo.ATENCIONES ON dbo.HONORARIOS_MEDICOS.ATE_CODIGO = dbo.ATENCIONES.ATE_CODIGO INNER JOIN      
                     dbo.PACIENTES ON dbo.ATENCIONES.PAC_CODIGO = dbo.PACIENTES.PAC_CODIGO LEFT OUTER JOIN      
                      dbo.FORMA_PAGO ON dbo.HONORARIOS_MEDICOS.FOR_CODIGO = dbo.FORMA_PAGO.FOR_CODIGO ON      
                       dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.HOM_CODIGO = dbo.HONORARIOS_MEDICOS.HOM_CODIGO LEFT OUTER JOIN      
                        dbo.RETENCIONES_FUENTE INNER JOIN      
                         dbo.MEDICOS ON dbo.RETENCIONES_FUENTE.RET_CODIGO = dbo.MEDICOS.RET_CODIGO ON dbo.HONORARIOS_MEDICOS.MED_CODIGO = dbo.MEDICOS.MED_CODIGO      
where dbo.HONORARIOS_MEDICOS_DATOSADICIONALES.GENERADO_ASIENTO<>1       
and HONORARIOS_MEDICOS.HOM_FACTURA_FECHA BETWEEN @fechaInicio and @fechaFinal      
AND HONORARIOS_MEDICOS_DATOSADICIONALES.HON_FUERA = @porFuera AND 
CONVERT(BIT, CASE WHEN (SELECT C.codclas FROM Sic3000..Clasificacion C 
INNER JOIN Sic3000..Forma_Pago FP ON C.codclas = FP.claspag WHERE FORMA_PAGO.forpag = FP.forpag) = 7 THEN 1 else 0 end) = @porSeguro
AND dbo.HONORARIOS_MEDICOS.ID_USUARIO = @id_usuario
