CREATE PROCEDURE sp_ParametroHabitacionPiso
AS
SELECT PAD_VALOR AS HABITACION, PAD_ACTIVO FROM PARAMETROS_DETALLE WHERE PAD_CODIGO = 33
GO

SELECT * FROM PARAMETROS ORDER BY 1 DESC

INSERT INTO PARAMETROS VALUES (22, 1, 'BLOQUEAR NIVEL PISO', 'BLOQUEAR COMBO DE PISOS', 1)

SELECT * FROM PARAMETROS_DETALLE ORDER BY 1 DESC

INSERT INTO PARAMETROS_DETALLE VALUES (33, 22, 'HABITACION POR DEFECTO', NULL, 'EMERGENCIA ALEMANIA', 1)
